"""
================================================================================
 Module : tests/test_integration_pipeline.py
 Purpose: Lightweight, source-only integration smoke test for CI / fresh clone.
          Builds a tiny SYNTHETIC SVG inline (no real MINERVA drawings — those
          are too large for CI) and runs the GeometryModel parser/classifier
          over it end-to-end.

          Asserts the core contract the engineering reviewer asked for:
            * the pipeline does NOT crash on a well-formed SVG,
            * >= 1 layer is discovered,
            * >= 1 drawable element is extracted,
            * >= 1 element is shape-classified,
            * text nodes are extracted (not silently dropped).

 Why synthetic: this test must pass on a fresh `git clone` with NO derived
 outputs present (data/model/ etc. are git-ignored and regenerated by
 ./make.sh). It depends only on tracked source under src/.

 Run standalone:  python3 tests/test_integration_pipeline.py
 Run via pytest:  PYTHONPATH=src python3 -m pytest tests/test_integration_pipeline.py -v
================================================================================
"""

import os
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))

from abacus_svg_pid import geometry as G  # noqa: E402


# A minimal but representative P&ID-like SVG: a viewBox, two named layer groups,
# a couple of coloured strokes (process lines), a filled circle (dot/instrument),
# a polyline (geometry) and two text tags. Colours sit on canonical anchors
# (BLUE -> A line, CYAN -> B line) so classification has something to bite on.
SYNTHETIC_SVG = """<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100">
  <g id="layer_process_lines" inkscape:label="ProcessLines"
     xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape">
    <path d="M 10 10 L 90 10" stroke="#0000FF" stroke-width="2" fill="none"/>
    <path d="M 10 30 L 90 30" style="stroke:#00FFFF;stroke-width:2" fill="none"/>
    <polyline points="10,50 50,50 50,90" stroke="#000000" fill="none"/>
  </g>
  <g id="layer_instruments" inkscape:label="Instruments"
     xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape">
    <circle cx="50" cy="10" r="3" fill="#FF0000"/>
    <rect x="20" y="60" width="10" height="6" fill="none" stroke="#808000"/>
    <text x="52" y="12" font-size="4">TT-101</text>
    <text x="22" y="58" font-size="4">CV-200</text>
  </g>
</svg>
"""


def _build_model():
    """Write the synthetic SVG to a temp file and parse it with GeometryModel."""
    tmpdir = tempfile.mkdtemp(prefix="pid_integration_")
    svg_path = os.path.join(tmpdir, "SYNTH.svg")
    with open(svg_path, "w") as fh:
        fh.write(SYNTHETIC_SVG)
    return G.GeometryModel("SYNTH", svg_path)


def test_pipeline_does_not_crash():
    """A well-formed SVG must parse without raising."""
    model = _build_model()
    assert model is not None
    assert model.viewbox == [0, 0, 100, 100]


def test_at_least_one_element_extracted():
    """>= 1 drawable element must be extracted."""
    model = _build_model()
    assert len(model.elements) >= 1, "no drawable elements extracted"


def test_at_least_one_shape_classified():
    """>= 1 element must receive a non-empty shape classification."""
    model = _build_model()
    shapes = [e.shape for e in model.elements if getattr(e, "shape", None)]
    assert len(shapes) >= 1, f"no shapes classified (elements={len(model.elements)})"


def test_text_nodes_extracted():
    """Text tags must be extracted, not silently dropped (governance: no
    silent deletion of unresolved data)."""
    model = _build_model()
    assert len(model.texts) >= 1, "text nodes were dropped"


def test_process_colours_detected():
    """At least one element should resolve to a canonical process code
    (BLUE -> A or CYAN -> B), proving colour classification runs."""
    model = _build_model()
    codes = {getattr(e, "process_code", None) for e in model.elements}
    codes.discard(None)
    codes.discard("none")
    # We do not over-assert the exact code set (classifier is heuristic); we
    # only require that colour classification produced *something* resolvable.
    assert len(codes) >= 1, f"no process codes resolved; got {codes}"


def _run_all():
    fns = [v for k, v in sorted(globals().items())
           if k.startswith("test_") and callable(v)]
    passed = 0
    for fn in fns:
        fn()
        print(f"  PASS  {fn.__name__}")
        passed += 1
    print(f"\n{passed}/{len(fns)} integration assertions passed.")
    return passed


if __name__ == "__main__":
    _run_all()
