#!/usr/bin/env python3
"""
make_report.py
==============
Reads the structured segmentation JSON produced by segment_pid.py and renders:

  * reports/process_logic_report.md  -- full process-logic segmentation report
  * reports/layer_breakdown.md       -- layer-by-layer breakdown for reconstruction
  * reports/layer_breakdown.json     -- machine-readable layer manifest

Pure standard library.
"""
import json
import os
from collections import Counter, defaultdict

import segment_pid as S  # reuse reference dictionaries

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "data")
REPORTS = os.path.join(HERE, "reports")
os.makedirs(REPORTS, exist_ok=True)


def load(key):
    with open(os.path.join(DATA, f"{key}_segmentation.json")) as f:
        return json.load(f)


def md_table(headers, rows):
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c) for c in r) + " |")
    return "\n".join(out)


def variable_breakdown(instruments):
    by_var = defaultdict(list)
    for i in instruments:
        by_var[i["variable"]].append(i)
    return by_var


def build_process_report(segs):
    L = []
    L.append("# MINERVA P&ID — Process-Logic Segmentation Report\n")
    L.append("**Project:** MINERVA CryoCell — Flow Schemes & Instrumentation  ")
    L.append("**Standard basis:** ISA 5.1 instrument tags · ISO A3 sheet · color-coded line classes  ")
    L.append("**Generated by:** `segment_pid.py` → `make_report.py`\n")
    L.append("This report segments every process-logic element extracted from the two source "
             "SVG P&IDs into the categories requested: process lines, equipment/components, "
             "instrumentation, vacuum barriers, temperature & pressure points, safety devices and "
             "color groups. All coordinates are in the shared SVG user space "
             "(`viewBox 0 0 1527.2727 1080`, ISO A3 landscape).\n")

    # ---- 1. Inventory at a glance ----
    L.append("## 1. Segmentation summary\n")
    rows = []
    for key, seg in segs.items():
        rows.append([
            key,
            len({i["tag"] for i in seg["instruments"]}),
            len(seg["equipment"]),
            len(seg["temperature_points"]),
            len(seg["pressure_points"]),
            len(seg["safety_devices"]),
            len(seg["vacuum_barriers"]),
            seg["instrument_bubbles"],
            len(seg["layers"]),
        ])
    L.append(md_table(
        ["Sheet", "Unique tags", "Equipment", "Temp pts", "Press pts",
         "Safety", "Vac. barriers", "Bubbles", "Layers"], rows))
    L.append("")

    # ---- 2. Process lines / color classes ----
    L.append("## 2. Process line segmentation (color-coded line classes)\n")
    L.append("Main process lines are segmented by their stroke color, which encodes the "
             "cryogenic line class. Specifications are taken from the drawing legend.\n")
    cls_rows = []
    for k, v in S.LINE_CLASSES.items():
        seg_counts = " / ".join(
            f"{key}:{len(seg['process_line_segments'].get(k, []))}"
            for key, seg in segs.items())
        cls_rows.append([k, v["color_name"], v["color"], v["temperature"],
                         v["pressure"], seg_counts, v["description"]])
    L.append(md_table(
        ["Class", "Color", "Hex", "Temp", "Pressure", "Segments (Q/RF)", "Description"],
        cls_rows))
    L.append("")
    L.append("> **WATER** (green `#00ff00`) segments are coupler / DI cooling-water utility "
             "lines (to FREIA) and are tracked separately from the helium line classes.\n")
    for key, seg in segs.items():
        pls = seg["process_line_segments"]
        L.append(f"**{key}** process-line segment counts: " +
                 ", ".join(f"`{k}`={len(v)}" for k, v in sorted(pls.items())))
        L.append("")

    # ---- 3. Equipment / components ----
    L.append("## 3. Equipment & component segmentation\n")
    for key, seg in segs.items():
        L.append(f"### {key}\n")
        kinds = Counter(e["kind"] for e in seg["equipment"])
        if kinds:
            L.append(md_table(["Component kind", "Count"],
                              sorted(kinds.items(), key=lambda x: -x[1])))
            L.append("")
            # list each with location
            rows = [[e["label"], e["kind"], e["x"], e["y"], e["layer"]]
                    for e in seg["equipment"]]
            L.append("<details><summary>Component instances with locations</summary>\n")
            L.append(md_table(["Label", "Kind", "x", "y", "Layer"], rows))
            L.append("\n</details>\n")
        else:
            L.append("_No discrete equipment labels detected on this sheet._\n")

    # ---- 4. Instrumentation (ISA 5.1) ----
    L.append("## 4. Instrumentation segmentation (ISA 5.1 tags)\n")
    L.append("Tags are parsed as `<2-letter prefix><number>` and categorized by measured "
             "variable and instrument role. The first letter encodes the measured variable "
             "(T, P, L, F …); trailing letters encode the function (T = transmitter, "
             "V = valve, S = switch, etc.).\n")
    for key, seg in segs.items():
        L.append(f"### {key}\n")
        by_prefix = Counter(i["prefix"] for i in seg["instruments"])
        rows = []
        for pfx, cnt in sorted(by_prefix.items(), key=lambda x: -x[1]):
            meaning, var, role = S.ISA_PREFIX[pfx]
            rows.append([pfx, meaning, var, role, cnt])
        L.append(md_table(["Prefix", "Meaning", "Variable", "Role", "Count"], rows))
        L.append("")
        # by variable group
        by_var = variable_breakdown(seg["instruments"])
        L.append("**By measured variable:** " +
                 ", ".join(f"`{v}`={len(items)}"
                           for v, items in sorted(by_var.items(), key=lambda x: -len(x[1]))))
        L.append("")

    # ---- 5. Temperature & pressure points ----
    L.append("## 5. Temperature & pressure measurement points\n")
    for key, seg in segs.items():
        L.append(f"### {key}\n")
        tt = [p for p in seg["temperature_points"] if p.get("tag")]
        tv = [p for p in seg["temperature_points"] if not p.get("tag")]
        pp = [p for p in seg["pressure_points"] if p.get("tag")]
        pv = [p for p in seg["pressure_points"] if not p.get("tag")]
        L.append(f"- **Temperature:** {len(tt)} tagged instruments (TT/TE/LT-thermometry) + "
                 f"{len(tv)} annotated temperature values.")
        L.append(f"- **Pressure:** {len(pp)} tagged instruments (PT/PZ/PL) + "
                 f"{len(pv)} annotated pressure values.\n")
        if tv:
            uniq = sorted({p["value"] for p in tv})
            L.append("Annotated temperature values found: " +
                     ", ".join(f"`{v}`" for v in uniq[:40]) + "\n")
        if pv:
            uniq = sorted({p["value"] for p in pv})
            L.append("Annotated pressure values found: " +
                     ", ".join(f"`{v}`" for v in uniq[:40]) + "\n")

    # ---- 6. Vacuum barriers + safety ----
    L.append("## 6. Vacuum barriers, safety devices & interlocks\n")
    for key, seg in segs.items():
        L.append(f"### {key}\n")
        vb = seg["vacuum_barriers"]
        L.append(f"**Vacuum barriers:** {len(vb)} element(s).")
        if vb:
            rows = [[v.get("type"), v.get("text", v.get("layer", "")),
                     v.get("x", ""), v.get("y", "")] for v in vb]
            L.append(md_table(["Type", "Text / Layer", "x", "y"], rows))
        L.append("")
        sd = seg["safety_devices"]
        L.append(f"**Safety devices (SV / RV / RD / PL / PZ):** {len(sd)}.")
        if sd:
            rows = [[d["tag"], d["meaning"], d["x"], d["y"], d["layer"]] for d in sd]
            L.append(md_table(["Tag", "Meaning", "x", "y", "Layer"], rows))
        L.append("")

    # ---- 7. Color segmentation ----
    L.append("## 7. Color-to-meaning mapping\n")
    L.append("Complete color coding system used across the drawings (stroke + fill colors). "
             "Confidence reflects how directly the meaning is anchored to the legend.\n")
    L.append(md_table(["Hex", "Group", "Meaning", "Confidence"],
                      [[c, m[0], m[1], m[2]] for c, m in
                       sorted(S.COLOR_MEANINGS.items())]))
    L.append("")
    for key, seg in segs.items():
        cg = seg["color_groups"]
        top = sorted(cg.items(), key=lambda x: -x[1])[:12]
        L.append(f"**{key}** top stroke colors: " +
                 ", ".join(f"`{c}`×{n}" for c, n in top))
        L.append("")

    return "\n".join(L)


def build_layer_report(segs):
    L = ["# Layer-by-Layer Breakdown (for reconstruction)\n"]
    L.append("Each source SVG is built from Inkscape layers. The tables below give the "
             "layer order (top→bottom as authored), with the text-label count per layer. "
             "Layers are grouped by their reconstruction role.\n")

    ROLE_KEYWORDS = [
        ("Piping / process lines", ["pip", "process line", "buffer", "intercept",
                                    "bottom line", "loop", "tee", "rf tee", "green pipe"]),
        ("Vacuum / barrier", ["vac", "invac", "qvb", "barrier"]),
        ("Equipment / vessels", ["vessel", "tank", "cplr", "cav", "coldmass", "header",
                                 "flange", "heater", "level gauge", "bottom connection",
                                 "metal", "limiter", "flowmeter", "tube"]),
        ("Instrumentation", ["instrument", "eh tt", "ehtt", "observer", "monitoring",
                             " tt", "pt", "ad, ed", "naming zone"]),
        ("Sub-systems / zones", ["rfcell", "he guard", "pemo", "qinfra", "qm", "users",
                                 "instrument air", "utilities", "tun", "tc-lb", "background"]),
        ("Annotation / legend", ["naming", "comment", "heat load", "terminal", "legend",
                                 "version", "scope", "pn level", "electrical", "condition",
                                 "text", "icon"]),
    ]

    def role_of(label):
        ll = (label or "").lower()
        for role, kws in ROLE_KEYWORDS:
            if any(k in ll for k in kws):
                return role
        return "Other / uncategorized"

    manifest = {}
    for key, seg in segs.items():
        L.append(f"## {key}\n")
        layers = seg["layers"]
        # group
        grouped = defaultdict(list)
        for ly in layers:
            grouped[role_of(ly["label"])].append(ly)
        manifest[key] = {"total_layers": len(layers), "groups": {}}
        for role, _kws in ROLE_KEYWORDS + [("Other / uncategorized", [])]:
            items = grouped.get(role, [])
            if not items:
                continue
            manifest[key]["groups"][role] = [
                {"id": i["id"], "label": i["label"], "text_count": i["text_count"]}
                for i in items]
            L.append(f"### {role}  ({len(items)} layers)\n")
            rows = [[i["label"] or i["id"], i["id"], i["text_count"]] for i in items]
            L.append(md_table(["Layer label", "id", "Text labels"], rows))
            L.append("")
    return "\n".join(L), manifest


def main():
    keys = ["QCELL-LB", "RFCELL"]
    segs = {k: load(k) for k in keys}

    proc = build_process_report(segs)
    with open(os.path.join(REPORTS, "process_logic_report.md"), "w") as f:
        f.write(proc)

    layer_md, manifest = build_layer_report(segs)
    with open(os.path.join(REPORTS, "layer_breakdown.md"), "w") as f:
        f.write(layer_md)
    with open(os.path.join(REPORTS, "layer_breakdown.json"), "w") as f:
        json.dump(manifest, f, indent=2)

    print("Reports written to", REPORTS)
    for fn in os.listdir(REPORTS):
        print("  ", fn)


if __name__ == "__main__":
    main()
